StockSearching/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search.urls')),
    path('admin/', admin.site.urls),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result'),
]

search/models.py
from django.db import models

# Create your models here.
class Stock(models.Model):
    code = models.CharField(max_length=50)
    date = models.DateField()
    open_price = models.FloatField()
    high_price = models.FloatField()
    low_price = models.FloatField()
    close_price = models.FloatField()
    volume = models.IntegerField()
    objects = models.Manager()

    def __str__(self):
        return self.code

search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Stock
import requests, json

API_KEY = 'OjdiNTAxYWIxMmNmZjAxZDI3YTIwNGQ4Zjc3YTBhZjIy'
URL_TEMP = 'https://api.intrinio.com/prices?identifier=%s&start_date=%s&end_date%s&api_key=%s'
STOCK_CODES = ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'FB', 'INTC', 'CSCO', 'CMCSA', 'PEP', 'NFLX', 'NVDA']

# Create your views here.
def index(request):
    return render(request, 'index.html', {'stock_codes': STOCK_CODES})

def result(request):
    
    if request.method == 'POST':
        
        start_date = request.POST.get('start')
        end_date = request.POST.get('end')
        stock_code = request.POST.get('code')

        request_url = URL_TEMP % (stock_code, start_date, end_date, API_KEY) 
        
        response = requests.get(request_url)
        
        response = response.json()

        data = response['data']

        if len(data) is not 0:
            stocks = Stock.objects.filter(code=stock_code)
            if(len(stocks)==0):
                for each in data:
                    write2db(stock_code, each)
            else:
                for each in data:
                    stock_in_db = False
                    for stock in stocks:
                        if each['date'] == str(stock.date):
                            stock_in_db = True
                            break
                    if not stock_in_db:
                        write2db(stock_code, each)

        return HttpResponse(
            json.dumps(data),
            content_type="application/json"
        )

# function write new stock record to db
def write2db(code, stock):
    new_stock = Stock(
        code = code,
        date = stock['date'],
        open_price = stock['open'],
        high_price = stock['high'],
        low_price = stock['low'],
        close_price = stock['close'],
        volume = stock['volume']
    )
    new_stock.save()

search/templates/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <title>{% block title %}
        
        {% endblock title %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/app.js' %}"></script>
    </head>
    
    <body>
        <div id="header">
            <div id="branding">
                <h1 id="site-name">US Stock Searching System</a></h1>
            </div>
        </div>
    
        <div id="content">
            <div class="content-main">
                <form action="result" method="post" id='search_form'>{% csrf_token %}
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border">Search Stock</legend>
                        <div class="info">
                                <label>Code: </label>
                                <select name="code" id="id_code">
                                    {% for code in stock_codes %}
                                        <option value="{{code}}">{{code}}</option>
                                    {% endfor %}
                                </select>
                        </div>
                        <div class="info">
                                <label>Start: </label>
                                <input type="date" name="start" required id="id_start" class="iput_box">
                        </div>
                        <div class="info">
                                <label>End: </label>
                                <input type="date" name="end" required id="id_end" class="iput_box">
                        </div>
                    </fieldset>
                    <div id="search">
                        <input type="submit" value="Search" name="_search" id="search_button">
                    </div>
                </form>
            </div>

            <div class="content-main">
                {% block result %}{% endblock %}
            </div>

            <div class="content-main">
                {% block chart %}
                  
                {% endblock chart %}
            </div>
        </div>    
        {% block javascript %}
        {% endblock javascript %}           
    </body>
</html>

search/templates/index.html
{% extends 'base.html' %}

{% block title %}
US Stock Search
{% endblock title %}

{% block result %}
<fieldset class="scheduler-border">
    <legend class="scheduler-border">Result</legend>
    <div id="result_field"></div>
</fieldset>
{% endblock result %}


{% block chart %}
<canvas id="myChart" width="700" height="400"></canvas>    
{% endblock chart %}
    

{% block javascript %}
<script>
    $('#search_form').on('submit', function(event) {
        event.preventDefault()
        console.log("form submitted!")
        search_stock()
    })

    // AJAX for post
    function search_stock() {
        console.log("searching is working!")
        $('#result_field').empty()
        $.ajax({
            url: "result",
            type: "POST",
            data: {
                code: $('#id_code').val(),
                start: $('#id_start').val(),
                end: $('#id_end').val(),
            },

            // handle a successful response
            success : function(json) {
                let length = json.length
                const labels = []
                const chart_data = []
                const max_period = []
                for (let i in json) {
                    let result = '<p>'+ json[i]['date'] + ' ' + json[i]['close'] + '</p>'
                    labels.unshift(json[i]['date'])
                    chart_data.unshift(json[i]['close'])
                    $('#result_field').append(result)
                }
                
                let max_profit = calculateMaxProfit(chart_data)
                console.log(max_profit)
                $('#result_field').prepend('<strong>Max Profit: '+ max_profit['profit'].toFixed(2) + '</strong>' )
                if(max_profit['profit'] > 0) {
                    for(let i = 0; i < chart_data.length; i++) {
                        if(i >= max_profit['start'] && i <= max_profit['end']) {
                            max_period.push(chart_data[i])
                            continue
                        }
                        if(i > max_profit['end']) {
                            break
                        }
                        max_period.push(null)
                    }
                }

                console.log(max_period)

                let ctx = document.getElementById("myChart").getContext('2d');

                let myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: labels,
                        datasets: [{
                            label: 'Max Profit',
                            data: max_period,
                            backgroundColor: [
                                'rgba(255, 0, 0, 0.2)',
                            ],
                            borderColor: [
                                'rgba(255, 0, 0, 1)',
                            ],
                            borderWidth: .5
                        },{
                            label: 'Overall Performance',
                            data: chart_data,
                            backgroundColor: [
                                'rgba(54, 162, 235, 0.2)',
                            ],
                            borderColor: [
                                'rgba(54, 162, 235, 1)',
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero:false
                                }
                            }]
                        }
                    }
                });
                console.log("success") // sanity check
            },

            // handle a non-successful response
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>") // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText) // provide a bit more info about the error to the console
            },
        })
    }

    // function to handle the algorithem of max profit calculation
    function calculateMaxProfit(chart_data) {

        let max_in_data = Math.max.apply(null, chart_data)
        let max_profit_period = {
            'profit': .0,
            'start': 0,
            'end': 0,
        }
        
        let data_len = chart_data.length
        
        for(let i = 0; i < data_len; i++) {

            if(chart_data[i] == max_in_data) continue

            for(let j = i+1; j < data_len; j++) {

                if(chart_data[i] < chart_data[j]) {
                    let profit = chart_data[j] - chart_data[i]
                    if(max_profit_period['profit'] < profit) {
                        max_profit_period['profit'] = profit
                        max_profit_period['start'] = parseInt(i)
                        max_profit_period['end'] = parseInt(j)
                    }
                }    

            }
        }
        return max_profit_period
    }
</script>
{% endblock javascript %}